close all;
clear all;
clc;

%% creat input info
[path_reuseable, sample_interval, speed_data_pre, ...
        reference_speed, l_bound, dl_bound, ddl_bound, dddl_bound, ...
        obstacle_avoid_bound, ego_para, init_state, end_state, ...
        distance_lon, reference_line, control_constraint, road_width, ...
        obstacle_bound, integral_step, lane_width, obs_info] = CreatInputInfo();
        
%% path planning algorithm
tic;
[path_data, path_solver_status, opt_solution] = PiecewiseJerkPathOptimizer( ...
        path_reuseable, sample_interval, l_bound, ...
        dl_bound, ddl_bound, dddl_bound, obstacle_avoid_bound, ...
        ego_para, init_state, end_state, integral_step);
toc;

%% result analysis
MyPlot(road_width, path_data, sample_interval, reference_speed, ...
        l_bound, dl_bound, ddl_bound, dddl_bound, obstacle_avoid_bound, ...
        ego_para, distance_lon, reference_line, control_constraint, ...
        obstacle_bound, integral_step, lane_width, obs_info);
